### ISSUE TITLE
Reading to memory instead of to disk

### ISSUE THREAD

**Issue by mikeseese** [gtreshchev/RuntimeFilesDownloader#2]
Thoughts about adding support to read to memory rather than to disk for small files? This would prevent users from having to then load the file (which I have a [free plugin for](https://www.unrealengine.com/marketplace/en-US/product/blueprint-file-sdk))

I could put together a pull request? I'd rather enhance your free open source plugin than make a new one 😅

**Comment by gtreshchev** [comment]
Hi,

This is a good idea, but I just thought that users may have their own aim
what to do with the imported file - for example, load an image, sound wave,
etc. This idea is very good, but it requires the implementation of each
case of the file action, and this is a rather difficult and time-consuming
task.

It would be really awesome if you enhance this plugin and add your own
features. The plugin is open-source and that's why you can just copy-paste
the sourcecode of files downloader

**Comment by mikeseese** [comment]
Ah I see what you mean; I was thinking of just text files where parsing the binary data isn't necessary. I'll go ahead and close this since I now realize the complexities of a general solution and unfortunately don't have the time currently to implement that much complexity. Thanks for the quick response!
